### ISSUE TITLE
Training fails for larger colmap dataset

### ISSUE THREAD

**Issue by adamblack** [nv-tlabs/3dgrut#95]
Hello,

I am having an issue while training a scene with a large set of images. I am using H100. When I train a scene with about 700 images (colmap dataset with masks), everything works fine, even with un-resized images with resolution of 4kx4k - both configs apps/colmap_3dgut.yam and apps/colmap_3dgut_mcmc.yaml work great.

I wanted to bump up the scene size so I increased my imageset to 1430 images and now both scenarios fail (even when I downscaled my images to 2 or 4 ratio). 

This is how I start the training process:

python train.py --config-name apps/colmap_3dgut.yaml path=/traindata/pr_large/train_dataset/ out_dir=runs experiment_name=pr_large export_ply.enabled=true optimizer.type=selective_adam dataset.downsample_factor=4

apps/colmap_3dgut.yam case: this scenario finishes, but loss is all over the place, results in final loss of about 0.73, negative PSNR, exported point cloud has most of the points located in the corners of cube (probably bounding box of the scene?)

apps/colmap_3dgut_mcmc.yaml case: loss is nan for about 1500 steps, then fails with an error:

File "/home/fs008/3dgrut/threedgrut/utils/misc.py", line 187, in _multinomial_sample
    return torch.multinomial(probabilities, n, replacement=replacement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Is there some limit regarding the number of images I can train on or maybe I am missing something else, some specific config settings?

I checked my colmap reconstruction and everything seems ok - all camera positions, camera definitions, intrinsics (6 different fisheye cameras) etc. and I was able to train the scene via different gaussian splatting implementation so input data seems to be ok.

Thank you for any hints.

**Comment by wilsonCernWq** [comment]
Hi @adamblack I am not aware of any limitation set on our side, you can try setting `CUDA_LAUNCH_BLOCKING=1` before running the training command to see which call triggers the error. This is an unexplored territory for so I am also curious about what might go wrong. Happy to help.

**Comment by adamblack** [comment]
So I did some more testing. My whole pipeline from preprocessing to training takes a few hours so I was not able to respond sooner. There is some weird randomness in colmap/glomap reconstruction that sometimes messes up reconstructed dataset which is no longer trainable in 3dgrut (but is ok for vanilla gaussian implementation or i.e. gsplat). However, after many iterations, I was able to edit my pipeline to produce trainable output for 3dgrut, especially for config apps/colmap_3dgut.yam.

Now even apps/colmap_3dgut_mcmc.yaml finishes successfully but exported ply is a random mess. But for smaller scene, up to 800 images, mcmc config works fine and produces superior results in comparison to apps/colmap_3dgut.yam. Any idea @wilsonCernWq why mcmc fails for larger dataset? If you would like me to share at least a reconstructed dataset I can manage that but not images since it is more than 7GB. However I understand if that might be out of the scope for this repository since mcmc is not your primary research topic (meaning the purpose of this project is probably not to troubleshoot mcmc :] ).

This is my reconstruction visualized in colmap:

![Image](https://github.com/user-attachments/assets/11fe75b8-af77-486a-ba14-6d1fd38121e5)

**Comment by adamblack** [comment]
Hello @zgojcic ,

thank you for a hint. So far I was not able to get some nice results but will keep trying (I still need to do distributed training of large dataset anyway so in worst case I just do more smaller chunks.)

Will keep this open for few days in case I find some nice solution to post, otherwise I will close this since it is skill issue on my side. :]

**Comment by adamblack** [comment]
So after several testing scenarios, I think I found somehow reasonable settings. I am not sure it will work for everybody since I also did some regularization changes in training logic, but the most impactful parts for me were options noise_lr and max_n_gaussians in mcmc config. What worked for me: 50000 for noise_lr and i.e. 4000000 for max_n_gaussians. Just a note, my dataset has cameras with wide FOV so I had to target a bigger resolution to get nice output. Which means, even after chunking the scene for separate runs, training VRAM load almost capped h100. (I am mentioning this to eventually save time for anybody trying to do this on a retail GPU) But in general it works great, just be sure to do chunking of input dataset. Closing the issue. Great project, looking forward to iterations! :]
